name: MELIStore CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    name: Build and Test (iOS)
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Set up project environment
        run: make setup

      - name: Resolve Swift package dependencies
        run: xcodebuild -resolvePackageDependencies -scheme MELIStore -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Build
        run: xcodebuild build -scheme MELIStore -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Run tests
        run: xcodebuild test -scheme MELIStore -destination 'platform=iOS Simulator,name=iPhone 15'
